DigitalDiscord: InternalPCO::Hub Class Reference
InternalPCO::Hub Class Reference
#include <InternalPrettyConsoleOut.h>
Public Member Functions
Hub (std::string name, std::vector< HubChoice > choices, std::string customLayout="STD")
void show ()
Public Attributes
bool hiding = true
std::vector< HubChoice > choices
std::string layout
std::string name
Detailed Description
Constructor & Destructor Documentation
Hub()
InternalPCO::Hub::Hub (std::string name, std::vector< HubChoice > choices, std::string customLayout = "STD")
{
     this->name = name;
     layout = customLayout;
     this->choices = choices;
 }
Member Function Documentation
show()
void InternalPCO::Hub::show ()
{
     hiding = false;
     mac::clearScreen();
     HubOpenEvent::trigger(this);
     if(layout == "STD") {
         std::cout << "-------------# Welcome to " << name << " #-------------\n";
     }
     else { //not STD
         std::cout <<
             IL::Parser()
                 .setIdents('{','}')
                 ->addPlaceHolder("name",this->name)
                 ->addPlaceHolder("time",std::to_string(time(NULL)))
                 ->addPlaceHolder("Ccount",std::to_string(choices.size()))
                 ->addPlaceHolder("nl","\n")
                 ->addPlaceHolder("{","{")
                 ->addPlaceHolder("}","}")
             ->parse(layout);
     }
     for(size_t i = 0; i < choices.size(); ++i) {
         std::cout << "       " << i+1 << ".)  " << choices[i].name << "\n";
     }
     std::cout << "\n\n"
               << "Your choice:";
     std::string inp;
     std::getline(std::cin,inp);
     mac::sleep(100);
     mac::clearScreen();
     try {
         DEBUG_MESSAGE("stoi: " << std::stoi(inp))
         if(std::stoi(std::string(1,inp[0])) > choices.size()) {
             ERROR_IF(true)
             errorMessage("Invaild Input in " + name + "-Hub");
             HubChoiceFailEvent::trigger(this);
             show();
         }
         choices[std::stoi(inp)-1].run();
     }
     catch(...) {
         errorMessage("Invaild Input in " + name + "-Hub");
         HubChoiceFailEvent::trigger(this);
         show();
     }
     hiding = true;
 }
References InternalLib::Parser::addPlaceHolder(), mac::clearScreen(), DEBUG_MESSAGE, ERROR_IF, InternalPCO::errorMessage(), InternalLib::Parser::parse(), InternalLib::Parser::setIdents(), mac::sleep(), and Event< FunPoint< InternalPCO::Hub * >, InternalPCO::Hub * >::trigger().
Member Data Documentation
choices
std::vector<HubChoice> InternalPCO::Hub::choices
hiding
bool InternalPCO::Hub::hiding = true
layout
std::string InternalPCO::Hub::layout
name
std::string InternalPCO::Hub::name
The documentation for this class was generated from the following files:
InternalPrettyConsoleOut.h
InternalPrettyConsoleOut.cpp