DigitalDiscord: Terminal Class Reference
Terminal Class Reference
#include <Terminal.h>
Public Member Functions
Terminal (std::string name, std::string layout=">>>")
std::string getName () const
std::string getLayout () const
Terminal * addFun (bool(*fun)(tokenType, Terminal *), std::string com)
void run ()
void stop ()
void operator= (const Terminal &ter)
void operator= (Terminal *ptr)
void operator= (std::string name)
Static Public Member Functions
static Terminal ptrToInst (Terminal *ptr)
static Terminal new_ (std::string name, std::string layout=">>>")
static Terminal InitMain ()
Public Attributes
std::vector< std::pair< bool(*)(tokenType, Terminal *), std::string > > funs
Static Public Attributes
static Terminal mainTerminal
Private Attributes
std::string layout
std::string name
bool canRun = true
Detailed Description
Constructor & Destructor Documentation
Terminal()
Terminal::Terminal (std::string name, std::string layout = ">>>") inline
         : name(name),layout(layout) {}
Member Function Documentation
addFun()
Terminal * Terminal::addFun (bool(*)(tokenType, Terminal *) fun, std::string com)
{
     funs.push_back(std::pair<bool(*)(tokenType,Terminal*),std::string>(fun,com));
     return this;
 }
References funs.
getLayout()
std::string Terminal::getLayout () const
{
     return layout;
 }
References layout.
getName()
std::string Terminal::getName () const
{
     return name;
 }
References name.
InitMain()
Terminal Terminal::InitMain () static
{
     //add all std commands here
     mainTerminal = Terminal::new_("MainTerminal","<<<>").addFun(
         [](tokenType tokens,Terminal* ptr)->bool{
             if(tokens.size() < 2) {
                 return true;
             }
             elif(tokens.size() < 4) {
                 if(tokens[2] == ">") {
                     InternalFsys::writeNormal(tokens[3],tokens[1],true);
                 }
                 else {
                     return true;
                 }
             }
             std::cout << tokens[1];
             return false;
         },
         "echo"
     )->addFun(
         [](tokenType tokens, Terminal* ptr)->bool {
             if(tokens.size() > 2) {
                 return true;
             }
             std::cout << "name:\t\t" << ptr->getName() << "\nlayout:\t\t" << ptr->getLayout() << "\ncommands:\t\t" << ptr->funs.size() << "\n";
         },
         "whoami"
     );
     return mainTerminal;
 }
References addFun(), elif, mainTerminal, and new_().
new_()
Terminal Terminal::new_ (std::string name, std::string layout = ">>>") static
{
     return Terminal(name,layout);
 }
References layout, name, and Terminal().
operator=() [1/3]
void Terminal::operator= (const Terminal & ter)
{
     this->funs = ter.funs;
     this->name = ter.name;
     this->layout = ter.layout;
 }
References funs, layout, and name.
operator=() [2/3]
void Terminal::operator= (std::string name)
{
     this->name = name;
     layout == "" ? ">>>" : layout; //set layout to ">>>" if there is no layout seted
 }
References layout, and name.
operator=() [3/3]
void Terminal::operator= (Terminal * ptr)
{
     operator=(ptrToInst(ptr));
 }
References operator=(), and ptrToInst().
ptrToInst()
static Terminal Terminal::ptrToInst (Terminal * ptr) inline static
{
         Terminal ret(ptr->getName(),ptr->getLayout());
         ret.funs = ptr->funs;
         return ret;
     }
References funs, getLayout(), and getName().
run()
void Terminal::run ()
                    {
     this->canRun = true;
     TerminalStartEvent::trigger(this);
     bool failed = false;
     std::string tmp;
     while(canRun) {
         std::cout << layout;
         std::getline(std::cin,tmp);
         if(tmp == "" || tmp == "\n") {
             TerminalExitEvent::trigger(this);
             break;
         }
         TerminalInputEvent::trigger(std::pair<std::string,Terminal*>(tmp,this));
         if(tmp == "exit") {
             TerminalExitEvent::trigger(this);
             break;
         }
         tokenType split = InternalFsys::splitTokens(" |",tmp);
         DEBUG_START_
             for(size_t i = 0; i < split.size(); ++i) {
                 std::cout << split[i] << "\n";
             }
         DEBUG_END_
         for(size_t i = 0; i < funs.size(); ++i) {
             DEBUG_MESSAGE("keyword:" << funs[i].second << " | " << "split[0]:" << split[0])
             if(split[0] == funs[i].second) {
                 failed = funs[i].first(split,this);
             }
         }
         if(failed) {
             TerminalFailEvent::trigger(std::pair<std::string,Terminal*>(tmp,this));
             //throw error and such stuff
         }
     }
 }
References canRun, DEBUG_END_, DEBUG_MESSAGE, DEBUG_START_, funs, layout, InternalFsys::splitTokens(), Event< FunPoint< std::pair< std::string, Terminal * > >, std::pair< std::string, Terminal * > >::trigger(), and Event< FunPoint< Terminal * >, Terminal * >::trigger().
stop()
void Terminal::stop ()
                     {
     this->canRun = false;
 }
References canRun.
Member Data Documentation
canRun
bool Terminal::canRun = true private
funs
std::vector<std::pair<bool(*)(tokenType,Terminal*),std::string> > Terminal::funs
layout
std::string Terminal::layout private
mainTerminal
Terminal Terminal::mainTerminal static
name
std::string Terminal::name private
The documentation for this class was generated from the following files:
Terminal.h
Terminal.cpp