DigitalDiscord: InternalPCO::LoadingScreen Class Reference
InternalPCO::LoadingScreen Class Reference
#include <InternalPrettyConsoleOut.h>
Public Member Functions
LoadingScreen (long length, int clearWaitTime, bool clearS, char logo)
bool next (std::string message="")
void clear (bool cls)
Public Attributes
long length = 0
bool clearS = false
int clearWaitTime = 0
char logo = '#'
Private Attributes
long tmp_len = 0
Detailed Description
Constructor & Destructor Documentation
LoadingScreen()
InternalPCO::LoadingScreen::LoadingScreen (long length, int clearWaitTime, bool clearS, char logo)
{
     this->length = length;
     this->clearS = clearS;
     this->clearWaitTime = clearWaitTime;
     this->logo = logo;
 }
Member Function Documentation
clear()
void InternalPCO::LoadingScreen::clear (bool cls)
{
     if(cls) { system("cls"); }
     tmp_len = 0;
 }
next()
bool InternalPCO::LoadingScreen::next (std::string message = "")
{
     LoadingScreenUpdateEvent::trigger(this);
     tmp_len += 1;
     std::cout << "\r";
     for(size_t i = 0; i < length + 40; ++i) {
         std::cout << " "; //clear line
     }
     std::cout << "\r[";
     for (long i = 0; i < length; ++i) {
         if (i > tmp_len) {
             std::cout << " ";
         }
         else {
             std::cout << logo;
         }
     }
     std::cout << "] " << message;
     if (tmp_len == length) {
         length = 0;
         tmp_len = 0;
         if (clearS) {
             mac::sleep(clearWaitTime);
             mac::clearScreen();
         }
         return true;
     }
     return false;
 }
References mac::clearScreen(), mac::sleep(), and Event< FunPoint< InternalPCO::LoadingScreen * >, InternalPCO::LoadingScreen * >::trigger().
Member Data Documentation
clearS
bool InternalPCO::LoadingScreen::clearS = false
clearWaitTime
int InternalPCO::LoadingScreen::clearWaitTime = 0
length
long InternalPCO::LoadingScreen::length = 0
logo
char InternalPCO::LoadingScreen::logo = '#'
tmp_len
long InternalPCO::LoadingScreen::tmp_len = 0 private
The documentation for this class was generated from the following files:
C:/Users/Fampu/source/repos/Gamehax0r/src/InternalPrettyConsoleOut.h
C:/Users/Fampu/source/repos/Gamehax0r/src/InternalPrettyConsoleOut.cpp