DigitalDiscord: InternalPCO::SlowPrintc Class Reference
InternalPCO::SlowPrintc Class Reference
#include <InternalPrettyConsoleOut.h>
Public Member Functions
std::string & getID ()
SlowPrintc * operator<< (const char *inp)
SlowPrintc * operator<< (std::string inp)
SlowPrintc * operator<< (int inp)
SlowPrintc * operator<< (char inp)
SlowPrintc * operator<< (long long inp)
void operator= (int time)
void operator++ ()
void operator-- ()
void setSleeptime (int newsleeptime)
Private Attributes
int sleeptime = 0
std::string id = "---"
Detailed Description
Member Function Documentation
getID()
std::string & InternalPCO::SlowPrintc::getID ()
{
     return id;
 }
References id.
operator++()
void InternalPCO::SlowPrintc::operator++ ()
{
     this->sleeptime += 1;
 }
operator--()
void InternalPCO::SlowPrintc::operator-- ()
{
     this->sleeptime -= 1;
 }
operator<<() [1/5]
InternalPCO::SlowPrintc * InternalPCO::SlowPrintc::operator<< (char inp)
{
     std::cout << inp;
     mac::sleep(sleeptime);
     SlowPrintClassPrintEvent::trigger(std::pair<std::string,SlowPrintc*>(std::to_string(inp),this));
     return this;
 }
References mac::sleep(), and Event< FunPoint< std::pair< std::string, InternalPCO::SlowPrintc * > >, std::pair< std::string, InternalPCO::SlowPrintc * > >::trigger().
operator<<() [2/5]
InternalPCO::SlowPrintc * InternalPCO::SlowPrintc::operator<< (const char * inp)
{
     for (size_t i = 0; i < strlen(inp); ++i) {
         std::cout << inp[i];
         mac::sleep(sleeptime);
     }
     SlowPrintClassPrintEvent::trigger(std::pair<std::string,SlowPrintc*>(inp,this));
     return this;
 }
References mac::sleep(), and Event< FunPoint< std::pair< std::string, InternalPCO::SlowPrintc * > >, std::pair< std::string, InternalPCO::SlowPrintc * > >::trigger().
operator<<() [3/5]
InternalPCO::SlowPrintc * InternalPCO::SlowPrintc::operator<< (int inp)
{
     for (long i = 0; i < inp; ++i) {
         std::cout << (std::to_string(inp))[i];
         mac::sleep(sleeptime);
     }
     SlowPrintClassPrintEvent::trigger(std::pair<std::string,SlowPrintc*>(std::to_string(inp),this));
     return this;
 }
References mac::sleep(), and Event< FunPoint< std::pair< std::string, InternalPCO::SlowPrintc * > >, std::pair< std::string, InternalPCO::SlowPrintc * > >::trigger().
operator<<() [4/5]
InternalPCO::SlowPrintc * InternalPCO::SlowPrintc::operator<< (long long inp)
{
     for (long i = 0; i < inp; ++i) {
         std::cout << std::to_string(inp)[i];
         mac::sleep(sleeptime);
     }
     SlowPrintClassPrintEvent::trigger(std::pair<std::string,SlowPrintc*>(std::to_string(inp),this));
     return this;
 }
References mac::sleep(), and Event< FunPoint< std::pair< std::string, InternalPCO::SlowPrintc * > >, std::pair< std::string, InternalPCO::SlowPrintc * > >::trigger().
operator<<() [5/5]
InternalPCO::SlowPrintc * InternalPCO::SlowPrintc::operator<< (std::string inp)
{
     for (size_t i = 0; i < inp.length(); ++i) {
         std::cout << inp[i];
         mac::sleep(sleeptime);
     }
     SlowPrintClassPrintEvent::trigger(std::pair<std::string,SlowPrintc*>(inp,this));
     return this;
 }
References mac::sleep(), and Event< FunPoint< std::pair< std::string, InternalPCO::SlowPrintc * > >, std::pair< std::string, InternalPCO::SlowPrintc * > >::trigger().
operator=()
void InternalPCO::SlowPrintc::operator= (int time)
{
     this->sleeptime = time;
 }
setSleeptime()
void InternalPCO::SlowPrintc::setSleeptime (int newsleeptime)
{
     sleeptime = newsleeptime;
 }
Member Data Documentation
id
std::string InternalPCO::SlowPrintc::id = "---" private
sleeptime
int InternalPCO::SlowPrintc::sleeptime = 0 private
The documentation for this class was generated from the following files:
InternalPrettyConsoleOut.h
InternalPrettyConsoleOut.cpp