DigitalDiscord: main.cpp File Reference
main.cpp File Reference
#include "InternalDef.h"
#include "CommandFile.h"
#include "InternalPrettyConsoleOut.h"
#include "InternalEvents.h"
#include "storage.h"
#include "Game.h"
#include "InternalSys.h"
#include "ExternalPlugins.h"
#include "Terminal.h"
#include "InternalErrorLogger.h"
#include "SpeakBubbles.h"
Macros
#define DEBUG_LEVEL 0
Functions
void sleepFor (time_t seconds)
int main ()
Macro Definition Documentation
DEBUG_LEVEL
#define DEBUG_LEVEL 0
Function Documentation
main()
int main ()
             {
     StorageSys::mainId = std::this_thread::get_id();
     Game::start();
     InternalPCO::Hub Menue("Start Screen",{InternalPCO::HubChoice([](){
     },"Start","StartChoice__01"),InternalPCO::HubChoice([](){
         exit(0);
     },"Exit","ExitChoice__02")});
     Chars::init(100);
     try {
     SpeakBubbles::initPrint();
     SpeakBubbles::hello();
     SpeakBubbles::firstQuest();
     }
     catch(std::exception& err) {
         std::cout << "an Error was catched: " << err.what() << "\n";
     }
 }
References SpeakBubbles::firstQuest(), SpeakBubbles::hello(), Chars::init(), SpeakBubbles::initPrint(), StorageSys::mainId, and Game::start().
sleepFor()
void sleepFor (time_t seconds)
{
     auto now = std::chrono::system_clock::now();
     while(true) {
         if(std::chrono::system_clock::to_time_t(std::chrono::system_clock::now()) >= std::chrono::system_clock::to_time_t(now) + seconds) {
             break;
         }
     }
 }