DigitalDiscord: Game Namespace Reference
Game Namespace Reference
Functions
void update ()
void start (bool showcase=false, int sleepTime=500)
Function Documentation
start()
void Game::start (bool showcase = false, int sleepTime = 500)
{
     if (showcase) {
         InternalPCO::LoadingScreen screen(10, 10, true, '#');
         screen.next("Check paths and gernerate them..."); //step 1
         System::doPaths();
         mac::sleep(sleepTime);
         screen.next("Look if all sys-Files are here...."); //step 2
         for(size_t i = 0; i < mac::allStdFiles.size(); ++i) {
             if(!fs::exists(System::pathtoDir + mac::allStdFiles[i])) {
                 InternalFsys::sys::makeFile(mac::allStdFiles[i],System::pathtoDir);
             }
         }
         mac::sleep(sleepTime);
         screen.next("Check if all files are here..."); //step 3
         InternalFileVec::update(System::pathtoDir);
         mac::sleep(sleepTime);
         screen.next("Set up plugins..."); //step 4
         ExternalPlugins::start();
         mac::sleep(sleepTime);
         screen.next("Start GameStartEvent..."); //step 5
         GameStartEvent::trigger();
         mac::sleep(sleepTime);
         screen.next("setup at-exit functions..."); //step 6
         std::atexit([](){
             onExit();
         });
         mac::sleep(sleepTime);
         screen.next("Init main-terminal..."); //step 7
         Terminal::InitMain();
         mac::sleep(sleepTime);
         screen.next("Setup chars sleep time..."); //step 8
         Chars::init();
         mac::sleep(sleepTime);
         screen.next("init SpeakBubbles sleap time..."); //step 9
         SpeakBubbles::initPrint();
         screen.clear(false);
     }
 }
References mac::allStdFiles, InternalPCO::LoadingScreen::clear(), System::doPaths(), Chars::init(), Terminal::InitMain(), SpeakBubbles::initPrint(), InternalFsys::sys::makeFile(), InternalPCO::LoadingScreen::next(), onExit(), System::pathtoDir, mac::sleep(), ExternalPlugins::start(), Event< funType, para >::trigger(), and InternalFileVec::update().
update()
void Game::update ()
                   {
     ExternalPlugins::update();
     using namespace Chars::Special;
     System::doPaths();
     GameUpdateEvent::trigger();
     if(std::this_thread::get_id() != StorageSys::mainId) {
         using namespace std::chrono_literals;
         std::this_thread::sleep_for(2000ms);
         DEBUG_WITH_FLUSH("update_wait with id:" << std::this_thread::get_id())
     }
 }
References DEBUG_WITH_FLUSH, System::doPaths(), StorageSys::mainId, Event< funType, para >::trigger(), and ExternalPlugins::update().